AJAX_LOADER_IMG = "<%= image_path('ajax-loader.gif') %>"
DEFAULT_CSS_TRANSITION_DURATION_MS = 250
ALLOCATION_HEIGHT = 30
WIDTH_OF_DAY = 16
WIDTH_OF_DESCRIPTOR = 192

`export { DEFAULT_CSS_TRANSITION_DURATION_MS, AJAX_LOADER_IMG, ALLOCATION_HEIGHT, WIDTH_OF_DAY, WIDTH_OF_DESCRIPTOR };`
